image: alpine/edge
packages:
  - go
  - hugo
  - rsync
sources:
  - https://github.com/Hackagotchi/hackagotchio.git
environment:
  kronos: deploy@kronos.devosmium.xyz
  # linode_instance: root@
secrets:
  - a88c3ffc-9bb0-451e-bf59-ef6198da6754
  - 0467a7c3-16d9-491c-9874-807bce4f2616
tasks:
  - build: |
      cd hackagotchio
      hugo
      #  - deploy: |
      #cd devosmium.xyz
      #rsync --delete -avz --exclude ".well-known" -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" public/ $kronos:/var/www/devosmium.xyz
      # rsync --delete -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" public/ $ec2_box:/var/www/tristan.partin.io
