baseURL = "https://gotchi.hackclub.com/"
languageCode = "en-us"
title = "Hackagotchi"

theme = "gotchi"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "Blog"
    url = "/blog/"

